### ISSUE TITLE
10.1.0: Cannot find module 'detective'

### ISSUE THREAD

**Issue by kud** [browserify/browserify#1242]
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kud/Projects/_playmedia/play-tv/node_modules/browserify/node_modules/module-deps/index.js:6:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Works well with `10.0.0`.

**Comment by jmm** [comment]
Please see [How to report issues with browserify](https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify), particularly the `example` section, and update your post accordingly.

**Comment by terinjokes** [comment]
@kud Can you `npm rm browserify` and `npm install browserify`. The dependency `module-deps` does define `detective` as a dependency.

**Comment by vinimxit** [comment]
How did you solve it?

**Comment by geoffreyhale** [comment]
```
npm rm browserify
npm install browserify
```
Worked for me.  Thanks @terinjokes.
